// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-n_TEa5zDII94Uz1ZlmRZ8XDETbf9tHc',
    appId: '1:300032426425:web:7d7880a098c891b18db668',
    messagingSenderId: '300032426425',
    projectId: 'sheeps-landing',
    authDomain: 'sheeps-landing.firebaseapp.com',
    storageBucket: 'sheeps-landing.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC3uD_dSPX8FNzCEtaPE-eZdDbQKivoWI',
    appId: '1:300032426425:android:9a8ba73910646a1c8db668',
    messagingSenderId: '300032426425',
    projectId: 'sheeps-landing',
    storageBucket: 'sheeps-landing.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCO3s72ogo553DtDoWsCBS_MCqQNnA72M8',
    appId: '1:300032426425:ios:3ca4411ed9377bdf8db668',
    messagingSenderId: '300032426425',
    projectId: 'sheeps-landing',
    storageBucket: 'sheeps-landing.appspot.com',
    iosBundleId: 'kr.sheeps.sheepsLanding',
  );
}
